server.port: ${SERVER_PORT:9088}
application-properties:
  binding-group: spring-base
  # One single point for reusability
  message-topic:
    new-comment-topic: new-comment
    new-post-topic: new-post
    new-subscriber-topic: new-subscriber
    new-post-following-topic: new-post-following
spring:
  application.name: spring-base-event
  cloud:
    function:
      definition: newPost;newSubscriber;newComment;newPostFollowing
    stream:
      bindings:
        newPost-in-0:
          destination: ${application-properties.message-topic.new-post-topic}
          group: ${application-properties.binding-group}
        newSubscriber-in-0:
          destination: ${application-properties.message-topic.new-subscriber-topic}
          group: ${application-properties.binding-group}
        newComment-in-0:
          destination: ${application-properties.message-topic.new-comment-topic}
          group: ${application-properties.binding-group}
        newPostFollowing-in-0:
          destination: ${application-properties.message-topic.new-post-following-topic}
          group: ${application-properties.binding-group}
      default-binder: rabbit
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:localhost:${MARIADB_PORT:3306}}/${MARIADB_DATABASE:myspringeventdatabase}
    username: ${MARIADB_USERNAME:root}
    password: ${MARIADB_PASSWORD:123456}
  liquibase.enabled: ${LIQUIBASE_ENABLED:true}
  output.ansi.enabled: ALWAYS
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:123456}
  threads.virtual.enabled: true